name: CI

on:
  push:
  pull_request:

jobs:
  testy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: requirements-lock.txt
      - run: pip install -r requirements-lock.txt
      - name: ruff
        run: python -m ruff check .
      - name: black
        run: python -m black --check .
      - name: pytest
        run: python -m pytest -q
